# Generated by Django 3.2 on 2024-04-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.CharField(max_length=255, verbose_name='Açıqlama')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.CharField(max_length=255, verbose_name='Açıqlama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Endirimli qiymət')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Məhsul adı')),
                ('description', models.TextField(verbose_name='Məhsul haqqında')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir?')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='Şəkil')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Bəyənilmə sayı')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Baxış sayı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişiklik tarixi')),
                ('details', models.ManyToManyField(to='products.Detail', verbose_name='Xüsusiyyətlər')),
                ('types', models.ManyToManyField(to='products.Types', verbose_name='Növlər')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Məzmun')),
                ('image', models.ImageField(upload_to='news/images/', verbose_name='Şəkil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dəyişiklik tarixi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Məhsul')),
            ],
        ),
    ]
